import { LoginButton } from "@/components/buttons";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: 'Sample APP',
  description: 'Generated by create next app',
}

export default function HomePage() {
  return (
    <div>
      <h1>Welcome to NextAuth App</h1>
      <p>
        <LoginButton></LoginButton>
      </p>
      <Link
        href="http://localhost:3001/table"
        rel="noopener noreferrer"
        target="_blank"
      >
        Home
      </Link>
    </div>
  );
}
